name: 更新版本号

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 设置 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: 安装依赖
        run: npm install

      - name: 更新版本号和生成CHANGELOG
        run: |
          npm version patch --no-git-tag-version
          npx auto-changelog -p
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'chore: 更新版本号和CHANGELOG'
          git push