name: 更新版本号

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 设置 Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: 安装依赖
        run: npm install

      - name: 运行 release-please-action
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node

      - name: 更新版本号、CHANGELOG 和 package.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'chore: 更新版本号'
          git push
        if: ${{ steps.release.outputs.release_created }}